### ISSUE TITLE
No module named 'pxr'

### ISSUE THREAD

**Issue by solort** [yoharol/Deformable_Simulation#1]
Hello! Thanks for your work.  When I was running the code，I encountered an ERROR "ModuleNotFoundError: No module named 'pxr'".
I cannot install this package using both pip and conda.How can I install this Python package?

Python=3.7.12，taichi=1.5.0

**Comment by yoharol** [comment]
Thank you for asking! You can refer to pxr [here](https://pypi.org/project/usd-core/)

**Comment by solort** [comment]
Very helpful, thank you!
